# Generated by Django 4.0.4 on 2022-05-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='occupation_id',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
